name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: sudo ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: Ltt.rs APK
        path: ./app/build/outputs/apk/**/Ltt.rs-*.apk
